version: '3.8'

services:
  employee-db:
    image: mysql:8.0
    container_name: employee-db
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: employee_db
      MYSQL_USER: employee_user
      MYSQL_PASSWORD: employeepass
    volumes:
      - employee-db-data:/var/lib/mysql
    networks:
      - soa-net

  employee-svc:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/pajovicv/employee-service:latest
    container_name: employee-svc
    depends_on:
      - employee-db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/storage
    networks:
      - soa-net

volumes:
  employee-db-data:

networks:
  soa-net:
    external: true
    name: soa-net
