services:
  employee-db:
    image: mysql:8.0
    container_name: employee-db
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: employee_db
      MYSQL_USER: employee_user
      MYSQL_PASSWORD: employeepass
    volumes:
      - employee-db-data:/var/lib/mysql
    networks:
      - soa-net

  employee-svc:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/pajovicv/employee-service:latest
    container_name: employee-svc
    depends_on:
      - employee-db
    ports:
      - "8010:8000"   # changed host port to avoid conflict
    volumes:
      - ./storage:/storage
    environment:
      DATABASE_URL: ${DATABASE_URL:-mysql+pymysql://employee_user:employeepass@employee-db:3306/employee_db}
      STORAGE_PATH: ${STORAGE_PATH:-./storage}
      COMPANY_SERVICE_URL: ${COMPANY_SERVICE_URL:-http://company-service:8082/api}
      COMPANY_HTTP_CONNECT_TIMEOUT: ${COMPANY_HTTP_CONNECT_TIMEOUT:-2.0}
      COMPANY_HTTP_READ_TIMEOUT: ${COMPANY_HTTP_READ_TIMEOUT:-2.0}
      COMPANY_VALIDATION_STRICT: ${COMPANY_VALIDATION_STRICT:-false}
      COMPANY_VALIDATION_ENABLED: ${COMPANY_VALIDATION_ENABLED:-true}
      FAAS_BASE_URL: ${FAAS_BASE_URL:-https://employee-utils-faas.onrender.com}
      FAAS_ENABLED: ${FAAS_ENABLED:-true}
      FAAS_CONNECT_TIMEOUT: ${FAAS_CONNECT_TIMEOUT:-2.0}
      FAAS_READ_TIMEOUT: ${FAAS_READ_TIMEOUT:-2.0}
      FAAS_AUDIT_ENABLED: ${FAAS_AUDIT_ENABLED:-true}
      FAAS_AUDIT_SERVICE: ${FAAS_AUDIT_SERVICE:-employee-service}
    networks:
      - soa-net

volumes:
  employee-db-data:

networks:
  soa-net:
    external: true
    name: soa-net
